// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RetryProducer is an autogenerated mock type for the RetryProducer type
type RetryProducer[T interface{}] struct {
	mock.Mock
}

type RetryProducer_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *RetryProducer[T]) EXPECT() *RetryProducer_Expecter[T] {
	return &RetryProducer_Expecter[T]{mock: &_m.Mock}
}

// Retry provides a mock function with given fields: ctx, event, currentRetry
func (_m *RetryProducer[T]) Retry(ctx context.Context, event T, currentRetry int) error {
	ret := _m.Called(ctx, event, currentRetry)

	if len(ret) == 0 {
		panic("no return value specified for Retry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, T, int) error); ok {
		r0 = rf(ctx, event, currentRetry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RetryProducer_Retry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Retry'
type RetryProducer_Retry_Call[T interface{}] struct {
	*mock.Call
}

// Retry is a helper method to define mock.On call
//   - ctx context.Context
//   - event T
//   - currentRetry int
func (_e *RetryProducer_Expecter[T]) Retry(ctx interface{}, event interface{}, currentRetry interface{}) *RetryProducer_Retry_Call[T] {
	return &RetryProducer_Retry_Call[T]{Call: _e.mock.On("Retry", ctx, event, currentRetry)}
}

func (_c *RetryProducer_Retry_Call[T]) Run(run func(ctx context.Context, event T, currentRetry int)) *RetryProducer_Retry_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(T), args[2].(int))
	})
	return _c
}

func (_c *RetryProducer_Retry_Call[T]) Return(_a0 error) *RetryProducer_Retry_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RetryProducer_Retry_Call[T]) RunAndReturn(run func(context.Context, T, int) error) *RetryProducer_Retry_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewRetryProducer creates a new instance of RetryProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRetryProducer[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *RetryProducer[T] {
	mock := &RetryProducer[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
