// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	kafka "github.com/segmentio/kafka-go"

	mock "github.com/stretchr/testify/mock"
)

// KafkaReader is an autogenerated mock type for the KafkaReader type
type KafkaReader struct {
	mock.Mock
}

type KafkaReader_Expecter struct {
	mock *mock.Mock
}

func (_m *KafkaReader) EXPECT() *KafkaReader_Expecter {
	return &KafkaReader_Expecter{mock: &_m.Mock}
}

// CommitMessages provides a mock function with given fields: ctx, msgs
func (_m *KafkaReader) CommitMessages(ctx context.Context, msgs ...kafka.Message) error {
	_va := make([]interface{}, len(msgs))
	for _i := range msgs {
		_va[_i] = msgs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CommitMessages")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...kafka.Message) error); ok {
		r0 = rf(ctx, msgs...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// KafkaReader_CommitMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitMessages'
type KafkaReader_CommitMessages_Call struct {
	*mock.Call
}

// CommitMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - msgs ...kafka.Message
func (_e *KafkaReader_Expecter) CommitMessages(ctx interface{}, msgs ...interface{}) *KafkaReader_CommitMessages_Call {
	return &KafkaReader_CommitMessages_Call{Call: _e.mock.On("CommitMessages",
		append([]interface{}{ctx}, msgs...)...)}
}

func (_c *KafkaReader_CommitMessages_Call) Run(run func(ctx context.Context, msgs ...kafka.Message)) *KafkaReader_CommitMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]kafka.Message, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(kafka.Message)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *KafkaReader_CommitMessages_Call) Return(_a0 error) *KafkaReader_CommitMessages_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *KafkaReader_CommitMessages_Call) RunAndReturn(run func(context.Context, ...kafka.Message) error) *KafkaReader_CommitMessages_Call {
	_c.Call.Return(run)
	return _c
}

// Config provides a mock function with no fields
func (_m *KafkaReader) Config() kafka.ReaderConfig {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 kafka.ReaderConfig
	if rf, ok := ret.Get(0).(func() kafka.ReaderConfig); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(kafka.ReaderConfig)
	}

	return r0
}

// KafkaReader_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type KafkaReader_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *KafkaReader_Expecter) Config() *KafkaReader_Config_Call {
	return &KafkaReader_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *KafkaReader_Config_Call) Run(run func()) *KafkaReader_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *KafkaReader_Config_Call) Return(_a0 kafka.ReaderConfig) *KafkaReader_Config_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *KafkaReader_Config_Call) RunAndReturn(run func() kafka.ReaderConfig) *KafkaReader_Config_Call {
	_c.Call.Return(run)
	return _c
}

// ReadMessage provides a mock function with given fields: ctx
func (_m *KafkaReader) ReadMessage(ctx context.Context) (kafka.Message, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReadMessage")
	}

	var r0 kafka.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (kafka.Message, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) kafka.Message); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(kafka.Message)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KafkaReader_ReadMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadMessage'
type KafkaReader_ReadMessage_Call struct {
	*mock.Call
}

// ReadMessage is a helper method to define mock.On call
//   - ctx context.Context
func (_e *KafkaReader_Expecter) ReadMessage(ctx interface{}) *KafkaReader_ReadMessage_Call {
	return &KafkaReader_ReadMessage_Call{Call: _e.mock.On("ReadMessage", ctx)}
}

func (_c *KafkaReader_ReadMessage_Call) Run(run func(ctx context.Context)) *KafkaReader_ReadMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *KafkaReader_ReadMessage_Call) Return(_a0 kafka.Message, _a1 error) *KafkaReader_ReadMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KafkaReader_ReadMessage_Call) RunAndReturn(run func(context.Context) (kafka.Message, error)) *KafkaReader_ReadMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewKafkaReader creates a new instance of KafkaReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKafkaReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *KafkaReader {
	mock := &KafkaReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
