// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/k1v4/drip_mate/internal/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IClothingRepository is an autogenerated mock type for the IClothingRepository type
type IClothingRepository struct {
	mock.Mock
}

type IClothingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IClothingRepository) EXPECT() *IClothingRepository_Expecter {
	return &IClothingRepository_Expecter{mock: &_m.Mock}
}

// CreateItem provides a mock function with given fields: ctx, req
func (_m *IClothingRepository) CreateItem(ctx context.Context, req *entity.CreateCatalogRequest) (*entity.Catalog, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateItem")
	}

	var r0 *entity.Catalog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.CreateCatalogRequest) (*entity.Catalog, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.CreateCatalogRequest) *entity.Catalog); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Catalog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.CreateCatalogRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IClothingRepository_CreateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItem'
type IClothingRepository_CreateItem_Call struct {
	*mock.Call
}

// CreateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entity.CreateCatalogRequest
func (_e *IClothingRepository_Expecter) CreateItem(ctx interface{}, req interface{}) *IClothingRepository_CreateItem_Call {
	return &IClothingRepository_CreateItem_Call{Call: _e.mock.On("CreateItem", ctx, req)}
}

func (_c *IClothingRepository_CreateItem_Call) Run(run func(ctx context.Context, req *entity.CreateCatalogRequest)) *IClothingRepository_CreateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.CreateCatalogRequest))
	})
	return _c
}

func (_c *IClothingRepository_CreateItem_Call) Return(_a0 *entity.Catalog, _a1 error) *IClothingRepository_CreateItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IClothingRepository_CreateItem_Call) RunAndReturn(run func(context.Context, *entity.CreateCatalogRequest) (*entity.Catalog, error)) *IClothingRepository_CreateItem_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteItem provides a mock function with given fields: ctx, id
func (_m *IClothingRepository) DeleteItem(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IClothingRepository_DeleteItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteItem'
type IClothingRepository_DeleteItem_Call struct {
	*mock.Call
}

// DeleteItem is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *IClothingRepository_Expecter) DeleteItem(ctx interface{}, id interface{}) *IClothingRepository_DeleteItem_Call {
	return &IClothingRepository_DeleteItem_Call{Call: _e.mock.On("DeleteItem", ctx, id)}
}

func (_c *IClothingRepository_DeleteItem_Call) Run(run func(ctx context.Context, id uuid.UUID)) *IClothingRepository_DeleteItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *IClothingRepository_DeleteItem_Call) Return(_a0 error) *IClothingRepository_DeleteItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IClothingRepository_DeleteItem_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *IClothingRepository_DeleteItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetItemByID provides a mock function with given fields: ctx, id
func (_m *IClothingRepository) GetItemByID(ctx context.Context, id uuid.UUID) (*entity.Catalog, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetItemByID")
	}

	var r0 *entity.Catalog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Catalog, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Catalog); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Catalog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IClothingRepository_GetItemByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItemByID'
type IClothingRepository_GetItemByID_Call struct {
	*mock.Call
}

// GetItemByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *IClothingRepository_Expecter) GetItemByID(ctx interface{}, id interface{}) *IClothingRepository_GetItemByID_Call {
	return &IClothingRepository_GetItemByID_Call{Call: _e.mock.On("GetItemByID", ctx, id)}
}

func (_c *IClothingRepository_GetItemByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *IClothingRepository_GetItemByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *IClothingRepository_GetItemByID_Call) Return(_a0 *entity.Catalog, _a1 error) *IClothingRepository_GetItemByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IClothingRepository_GetItemByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Catalog, error)) *IClothingRepository_GetItemByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItem provides a mock function with given fields: ctx, req
func (_m *IClothingRepository) UpdateItem(ctx context.Context, req *entity.UpdateCatalogRequest) (*entity.Catalog, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItem")
	}

	var r0 *entity.Catalog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UpdateCatalogRequest) (*entity.Catalog, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UpdateCatalogRequest) *entity.Catalog); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Catalog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.UpdateCatalogRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IClothingRepository_UpdateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItem'
type IClothingRepository_UpdateItem_Call struct {
	*mock.Call
}

// UpdateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entity.UpdateCatalogRequest
func (_e *IClothingRepository_Expecter) UpdateItem(ctx interface{}, req interface{}) *IClothingRepository_UpdateItem_Call {
	return &IClothingRepository_UpdateItem_Call{Call: _e.mock.On("UpdateItem", ctx, req)}
}

func (_c *IClothingRepository_UpdateItem_Call) Run(run func(ctx context.Context, req *entity.UpdateCatalogRequest)) *IClothingRepository_UpdateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.UpdateCatalogRequest))
	})
	return _c
}

func (_c *IClothingRepository_UpdateItem_Call) Return(_a0 *entity.Catalog, _a1 error) *IClothingRepository_UpdateItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IClothingRepository_UpdateItem_Call) RunAndReturn(run func(context.Context, *entity.UpdateCatalogRequest) (*entity.Catalog, error)) *IClothingRepository_UpdateItem_Call {
	_c.Call.Return(run)
	return _c
}

// NewIClothingRepository creates a new instance of IClothingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIClothingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IClothingRepository {
	mock := &IClothingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
