version: "2"

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - errcheck
    - gocritic
    - gocyclo
    - goconst
    - unconvert
    - unparam
    - unused
    - nakedret
    - prealloc
    - bodyclose
    - noctx
    - misspell
    - exhaustive

  settings:
    gocyclo:
      min-complexity: 15
    gocritic:
      enabled-tags:
        - performance
        - diagnostic
    exhaustive:
      default-signifies-exhaustive: true

formatters:
  enable:
    - goimports

issues:
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - errcheck