version: "2"

linters:
  default: none
  enable:
    - goconst
    - gocritic
    - gocyclo
    - govet
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec