// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/k1v4/drip_mate/internal/modules/notification_service/entity"
	mock "github.com/stretchr/testify/mock"
)

// IHandler is an autogenerated mock type for the IHandler type
type IHandler struct {
	mock.Mock
}

type IHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *IHandler) EXPECT() *IHandler_Expecter {
	return &IHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: ctx, msg
func (_m *IHandler) Handle(ctx context.Context, msg entity.Message) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Message) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type IHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - msg entity.Message
func (_e *IHandler_Expecter) Handle(ctx interface{}, msg interface{}) *IHandler_Handle_Call {
	return &IHandler_Handle_Call{Call: _e.mock.On("Handle", ctx, msg)}
}

func (_c *IHandler_Handle_Call) Run(run func(ctx context.Context, msg entity.Message)) *IHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Message))
	})
	return _c
}

func (_c *IHandler_Handle_Call) Return(_a0 error) *IHandler_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IHandler_Handle_Call) RunAndReturn(run func(context.Context, entity.Message) error) *IHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewIHandler creates a new instance of IHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *IHandler {
	mock := &IHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
