// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/k1v4/drip_mate/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// ReferenceRepo is an autogenerated mock type for the ReferenceRepo type
type ReferenceRepo struct {
	mock.Mock
}

type ReferenceRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *ReferenceRepo) EXPECT() *ReferenceRepo_Expecter {
	return &ReferenceRepo_Expecter{mock: &_m.Mock}
}

// GetCategories provides a mock function with given fields: ctx
func (_m *ReferenceRepo) GetCategories(ctx context.Context) ([]entity.Category, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCategories")
	}

	var r0 []entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.Category, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Category); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReferenceRepo_GetCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategories'
type ReferenceRepo_GetCategories_Call struct {
	*mock.Call
}

// GetCategories is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ReferenceRepo_Expecter) GetCategories(ctx interface{}) *ReferenceRepo_GetCategories_Call {
	return &ReferenceRepo_GetCategories_Call{Call: _e.mock.On("GetCategories", ctx)}
}

func (_c *ReferenceRepo_GetCategories_Call) Run(run func(ctx context.Context)) *ReferenceRepo_GetCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ReferenceRepo_GetCategories_Call) Return(_a0 []entity.Category, _a1 error) *ReferenceRepo_GetCategories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReferenceRepo_GetCategories_Call) RunAndReturn(run func(context.Context) ([]entity.Category, error)) *ReferenceRepo_GetCategories_Call {
	_c.Call.Return(run)
	return _c
}

// GetColors provides a mock function with given fields: ctx
func (_m *ReferenceRepo) GetColors(ctx context.Context) ([]entity.ColorType, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetColors")
	}

	var r0 []entity.ColorType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.ColorType, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.ColorType); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ColorType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReferenceRepo_GetColors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetColors'
type ReferenceRepo_GetColors_Call struct {
	*mock.Call
}

// GetColors is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ReferenceRepo_Expecter) GetColors(ctx interface{}) *ReferenceRepo_GetColors_Call {
	return &ReferenceRepo_GetColors_Call{Call: _e.mock.On("GetColors", ctx)}
}

func (_c *ReferenceRepo_GetColors_Call) Run(run func(ctx context.Context)) *ReferenceRepo_GetColors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ReferenceRepo_GetColors_Call) Return(_a0 []entity.ColorType, _a1 error) *ReferenceRepo_GetColors_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReferenceRepo_GetColors_Call) RunAndReturn(run func(context.Context) ([]entity.ColorType, error)) *ReferenceRepo_GetColors_Call {
	_c.Call.Return(run)
	return _c
}

// GetMusics provides a mock function with given fields: ctx
func (_m *ReferenceRepo) GetMusics(ctx context.Context) ([]entity.MusicType, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMusics")
	}

	var r0 []entity.MusicType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.MusicType, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.MusicType); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.MusicType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReferenceRepo_GetMusics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMusics'
type ReferenceRepo_GetMusics_Call struct {
	*mock.Call
}

// GetMusics is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ReferenceRepo_Expecter) GetMusics(ctx interface{}) *ReferenceRepo_GetMusics_Call {
	return &ReferenceRepo_GetMusics_Call{Call: _e.mock.On("GetMusics", ctx)}
}

func (_c *ReferenceRepo_GetMusics_Call) Run(run func(ctx context.Context)) *ReferenceRepo_GetMusics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ReferenceRepo_GetMusics_Call) Return(_a0 []entity.MusicType, _a1 error) *ReferenceRepo_GetMusics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReferenceRepo_GetMusics_Call) RunAndReturn(run func(context.Context) ([]entity.MusicType, error)) *ReferenceRepo_GetMusics_Call {
	_c.Call.Return(run)
	return _c
}

// GetSeasons provides a mock function with given fields: ctx
func (_m *ReferenceRepo) GetSeasons(ctx context.Context) ([]entity.Season, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSeasons")
	}

	var r0 []entity.Season
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.Season, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Season); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Season)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReferenceRepo_GetSeasons_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSeasons'
type ReferenceRepo_GetSeasons_Call struct {
	*mock.Call
}

// GetSeasons is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ReferenceRepo_Expecter) GetSeasons(ctx interface{}) *ReferenceRepo_GetSeasons_Call {
	return &ReferenceRepo_GetSeasons_Call{Call: _e.mock.On("GetSeasons", ctx)}
}

func (_c *ReferenceRepo_GetSeasons_Call) Run(run func(ctx context.Context)) *ReferenceRepo_GetSeasons_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ReferenceRepo_GetSeasons_Call) Return(_a0 []entity.Season, _a1 error) *ReferenceRepo_GetSeasons_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReferenceRepo_GetSeasons_Call) RunAndReturn(run func(context.Context) ([]entity.Season, error)) *ReferenceRepo_GetSeasons_Call {
	_c.Call.Return(run)
	return _c
}

// GetStyles provides a mock function with given fields: ctx
func (_m *ReferenceRepo) GetStyles(ctx context.Context) ([]entity.StyleType, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStyles")
	}

	var r0 []entity.StyleType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.StyleType, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.StyleType); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.StyleType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReferenceRepo_GetStyles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStyles'
type ReferenceRepo_GetStyles_Call struct {
	*mock.Call
}

// GetStyles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ReferenceRepo_Expecter) GetStyles(ctx interface{}) *ReferenceRepo_GetStyles_Call {
	return &ReferenceRepo_GetStyles_Call{Call: _e.mock.On("GetStyles", ctx)}
}

func (_c *ReferenceRepo_GetStyles_Call) Run(run func(ctx context.Context)) *ReferenceRepo_GetStyles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ReferenceRepo_GetStyles_Call) Return(_a0 []entity.StyleType, _a1 error) *ReferenceRepo_GetStyles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReferenceRepo_GetStyles_Call) RunAndReturn(run func(context.Context) ([]entity.StyleType, error)) *ReferenceRepo_GetStyles_Call {
	_c.Call.Return(run)
	return _c
}

// NewReferenceRepo creates a new instance of ReferenceRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReferenceRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReferenceRepo {
	mock := &ReferenceRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
