// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/k1v4/drip_mate/internal/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IRecommendationUseCase is an autogenerated mock type for the IRecommendationUseCase type
type IRecommendationUseCase struct {
	mock.Mock
}

type IRecommendationUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *IRecommendationUseCase) EXPECT() *IRecommendationUseCase_Expecter {
	return &IRecommendationUseCase_Expecter{mock: &_m.Mock}
}

// GetUserRecommendation provides a mock function with given fields: ctx, formality, userID
func (_m *IRecommendationUseCase) GetUserRecommendation(ctx context.Context, formality int, userID uuid.UUID) ([]entity.Catalog, error) {
	ret := _m.Called(ctx, formality, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRecommendation")
	}

	var r0 []entity.Catalog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, uuid.UUID) ([]entity.Catalog, error)); ok {
		return rf(ctx, formality, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, uuid.UUID) []entity.Catalog); ok {
		r0 = rf(ctx, formality, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Catalog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, uuid.UUID) error); ok {
		r1 = rf(ctx, formality, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IRecommendationUseCase_GetUserRecommendation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRecommendation'
type IRecommendationUseCase_GetUserRecommendation_Call struct {
	*mock.Call
}

// GetUserRecommendation is a helper method to define mock.On call
//   - ctx context.Context
//   - formality int
//   - userID uuid.UUID
func (_e *IRecommendationUseCase_Expecter) GetUserRecommendation(ctx interface{}, formality interface{}, userID interface{}) *IRecommendationUseCase_GetUserRecommendation_Call {
	return &IRecommendationUseCase_GetUserRecommendation_Call{Call: _e.mock.On("GetUserRecommendation", ctx, formality, userID)}
}

func (_c *IRecommendationUseCase_GetUserRecommendation_Call) Run(run func(ctx context.Context, formality int, userID uuid.UUID)) *IRecommendationUseCase_GetUserRecommendation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *IRecommendationUseCase_GetUserRecommendation_Call) Return(_a0 []entity.Catalog, _a1 error) *IRecommendationUseCase_GetUserRecommendation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IRecommendationUseCase_GetUserRecommendation_Call) RunAndReturn(run func(context.Context, int, uuid.UUID) ([]entity.Catalog, error)) *IRecommendationUseCase_GetUserRecommendation_Call {
	_c.Call.Return(run)
	return _c
}

// NewIRecommendationUseCase creates a new instance of IRecommendationUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRecommendationUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRecommendationUseCase {
	mock := &IRecommendationUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
