// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IUploadService is an autogenerated mock type for the IUploadService type
type IUploadService struct {
	mock.Mock
}

type IUploadService_Expecter struct {
	mock *mock.Mock
}

func (_m *IUploadService) EXPECT() *IUploadService_Expecter {
	return &IUploadService_Expecter{mock: &_m.Mock}
}

// DeleteImage provides a mock function with given fields: ctx, url
func (_m *IUploadService) DeleteImage(ctx context.Context, url string) (bool, error) {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for DeleteImage")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, url)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IUploadService_DeleteImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteImage'
type IUploadService_DeleteImage_Call struct {
	*mock.Call
}

// DeleteImage is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *IUploadService_Expecter) DeleteImage(ctx interface{}, url interface{}) *IUploadService_DeleteImage_Call {
	return &IUploadService_DeleteImage_Call{Call: _e.mock.On("DeleteImage", ctx, url)}
}

func (_c *IUploadService_DeleteImage_Call) Run(run func(ctx context.Context, url string)) *IUploadService_DeleteImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IUploadService_DeleteImage_Call) Return(_a0 bool, _a1 error) *IUploadService_DeleteImage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IUploadService_DeleteImage_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *IUploadService_DeleteImage_Call {
	_c.Call.Return(run)
	return _c
}

// UploadImage provides a mock function with given fields: ctx, fileName, imageData
func (_m *IUploadService) UploadImage(ctx context.Context, fileName string, imageData []byte) (string, error) {
	ret := _m.Called(ctx, fileName, imageData)

	if len(ret) == 0 {
		panic("no return value specified for UploadImage")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) (string, error)); ok {
		return rf(ctx, fileName, imageData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) string); ok {
		r0 = rf(ctx, fileName, imageData)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, fileName, imageData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IUploadService_UploadImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadImage'
type IUploadService_UploadImage_Call struct {
	*mock.Call
}

// UploadImage is a helper method to define mock.On call
//   - ctx context.Context
//   - fileName string
//   - imageData []byte
func (_e *IUploadService_Expecter) UploadImage(ctx interface{}, fileName interface{}, imageData interface{}) *IUploadService_UploadImage_Call {
	return &IUploadService_UploadImage_Call{Call: _e.mock.On("UploadImage", ctx, fileName, imageData)}
}

func (_c *IUploadService_UploadImage_Call) Run(run func(ctx context.Context, fileName string, imageData []byte)) *IUploadService_UploadImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *IUploadService_UploadImage_Call) Return(_a0 string, _a1 error) *IUploadService_UploadImage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IUploadService_UploadImage_Call) RunAndReturn(run func(context.Context, string, []byte) (string, error)) *IUploadService_UploadImage_Call {
	_c.Call.Return(run)
	return _c
}

// NewIUploadService creates a new instance of IUploadService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUploadService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUploadService {
	mock := &IUploadService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
