// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/k1v4/drip_mate/internal/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IRecommendationRepository is an autogenerated mock type for the IRecommendationRepository type
type IRecommendationRepository struct {
	mock.Mock
}

type IRecommendationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IRecommendationRepository) EXPECT() *IRecommendationRepository_Expecter {
	return &IRecommendationRepository_Expecter{mock: &_m.Mock}
}

// GetUserProfile provides a mock function with given fields: ctx, userID
func (_m *IRecommendationRepository) GetUserProfile(ctx context.Context, userID uuid.UUID) (*entity.UserProfile, string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserProfile")
	}

	var r0 *entity.UserProfile
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.UserProfile, string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.UserProfile); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) string); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = rf(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// IRecommendationRepository_GetUserProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserProfile'
type IRecommendationRepository_GetUserProfile_Call struct {
	*mock.Call
}

// GetUserProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *IRecommendationRepository_Expecter) GetUserProfile(ctx interface{}, userID interface{}) *IRecommendationRepository_GetUserProfile_Call {
	return &IRecommendationRepository_GetUserProfile_Call{Call: _e.mock.On("GetUserProfile", ctx, userID)}
}

func (_c *IRecommendationRepository_GetUserProfile_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *IRecommendationRepository_GetUserProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *IRecommendationRepository_GetUserProfile_Call) Return(_a0 *entity.UserProfile, _a1 string, _a2 error) *IRecommendationRepository_GetUserProfile_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *IRecommendationRepository_GetUserProfile_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.UserProfile, string, error)) *IRecommendationRepository_GetUserProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewIRecommendationRepository creates a new instance of IRecommendationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRecommendationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRecommendationRepository {
	mock := &IRecommendationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
