// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IUploadRepository is an autogenerated mock type for the IUploadRepository type
type IUploadRepository struct {
	mock.Mock
}

type IUploadRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IUploadRepository) EXPECT() *IUploadRepository_Expecter {
	return &IUploadRepository_Expecter{mock: &_m.Mock}
}

// DeleteImage provides a mock function with given fields: ctx, fileName
func (_m *IUploadRepository) DeleteImage(ctx context.Context, fileName string) error {
	ret := _m.Called(ctx, fileName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, fileName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IUploadRepository_DeleteImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteImage'
type IUploadRepository_DeleteImage_Call struct {
	*mock.Call
}

// DeleteImage is a helper method to define mock.On call
//   - ctx context.Context
//   - fileName string
func (_e *IUploadRepository_Expecter) DeleteImage(ctx interface{}, fileName interface{}) *IUploadRepository_DeleteImage_Call {
	return &IUploadRepository_DeleteImage_Call{Call: _e.mock.On("DeleteImage", ctx, fileName)}
}

func (_c *IUploadRepository_DeleteImage_Call) Run(run func(ctx context.Context, fileName string)) *IUploadRepository_DeleteImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IUploadRepository_DeleteImage_Call) Return(_a0 error) *IUploadRepository_DeleteImage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IUploadRepository_DeleteImage_Call) RunAndReturn(run func(context.Context, string) error) *IUploadRepository_DeleteImage_Call {
	_c.Call.Return(run)
	return _c
}

// UploadImage provides a mock function with given fields: ctx, fileName, imageData
func (_m *IUploadRepository) UploadImage(ctx context.Context, fileName string, imageData []byte) (string, error) {
	ret := _m.Called(ctx, fileName, imageData)

	if len(ret) == 0 {
		panic("no return value specified for UploadImage")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) (string, error)); ok {
		return rf(ctx, fileName, imageData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) string); ok {
		r0 = rf(ctx, fileName, imageData)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, fileName, imageData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IUploadRepository_UploadImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadImage'
type IUploadRepository_UploadImage_Call struct {
	*mock.Call
}

// UploadImage is a helper method to define mock.On call
//   - ctx context.Context
//   - fileName string
//   - imageData []byte
func (_e *IUploadRepository_Expecter) UploadImage(ctx interface{}, fileName interface{}, imageData interface{}) *IUploadRepository_UploadImage_Call {
	return &IUploadRepository_UploadImage_Call{Call: _e.mock.On("UploadImage", ctx, fileName, imageData)}
}

func (_c *IUploadRepository_UploadImage_Call) Run(run func(ctx context.Context, fileName string, imageData []byte)) *IUploadRepository_UploadImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *IUploadRepository_UploadImage_Call) Return(_a0 string, _a1 error) *IUploadRepository_UploadImage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IUploadRepository_UploadImage_Call) RunAndReturn(run func(context.Context, string, []byte) (string, error)) *IUploadRepository_UploadImage_Call {
	_c.Call.Return(run)
	return _c
}

// NewIUploadRepository creates a new instance of IUploadRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUploadRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUploadRepository {
	mock := &IUploadRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
