// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/k1v4/drip_mate/internal/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IClothingUseCase is an autogenerated mock type for the IClothingUseCase type
type IClothingUseCase struct {
	mock.Mock
}

type IClothingUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *IClothingUseCase) EXPECT() *IClothingUseCase_Expecter {
	return &IClothingUseCase_Expecter{mock: &_m.Mock}
}

// CreateItem provides a mock function with given fields: ctx, req, fileName, imageData
func (_m *IClothingUseCase) CreateItem(ctx context.Context, req *entity.CreateCatalogRequest, fileName string, imageData []byte) (*entity.Catalog, error) {
	ret := _m.Called(ctx, req, fileName, imageData)

	if len(ret) == 0 {
		panic("no return value specified for CreateItem")
	}

	var r0 *entity.Catalog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.CreateCatalogRequest, string, []byte) (*entity.Catalog, error)); ok {
		return rf(ctx, req, fileName, imageData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.CreateCatalogRequest, string, []byte) *entity.Catalog); ok {
		r0 = rf(ctx, req, fileName, imageData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Catalog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.CreateCatalogRequest, string, []byte) error); ok {
		r1 = rf(ctx, req, fileName, imageData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IClothingUseCase_CreateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItem'
type IClothingUseCase_CreateItem_Call struct {
	*mock.Call
}

// CreateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entity.CreateCatalogRequest
//   - fileName string
//   - imageData []byte
func (_e *IClothingUseCase_Expecter) CreateItem(ctx interface{}, req interface{}, fileName interface{}, imageData interface{}) *IClothingUseCase_CreateItem_Call {
	return &IClothingUseCase_CreateItem_Call{Call: _e.mock.On("CreateItem", ctx, req, fileName, imageData)}
}

func (_c *IClothingUseCase_CreateItem_Call) Run(run func(ctx context.Context, req *entity.CreateCatalogRequest, fileName string, imageData []byte)) *IClothingUseCase_CreateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.CreateCatalogRequest), args[2].(string), args[3].([]byte))
	})
	return _c
}

func (_c *IClothingUseCase_CreateItem_Call) Return(_a0 *entity.Catalog, _a1 error) *IClothingUseCase_CreateItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IClothingUseCase_CreateItem_Call) RunAndReturn(run func(context.Context, *entity.CreateCatalogRequest, string, []byte) (*entity.Catalog, error)) *IClothingUseCase_CreateItem_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteItem provides a mock function with given fields: ctx, id
func (_m *IClothingUseCase) DeleteItem(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IClothingUseCase_DeleteItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteItem'
type IClothingUseCase_DeleteItem_Call struct {
	*mock.Call
}

// DeleteItem is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *IClothingUseCase_Expecter) DeleteItem(ctx interface{}, id interface{}) *IClothingUseCase_DeleteItem_Call {
	return &IClothingUseCase_DeleteItem_Call{Call: _e.mock.On("DeleteItem", ctx, id)}
}

func (_c *IClothingUseCase_DeleteItem_Call) Run(run func(ctx context.Context, id uuid.UUID)) *IClothingUseCase_DeleteItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *IClothingUseCase_DeleteItem_Call) Return(_a0 error) *IClothingUseCase_DeleteItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IClothingUseCase_DeleteItem_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *IClothingUseCase_DeleteItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetItemByID provides a mock function with given fields: ctx, id
func (_m *IClothingUseCase) GetItemByID(ctx context.Context, id uuid.UUID) (*entity.Catalog, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetItemByID")
	}

	var r0 *entity.Catalog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Catalog, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Catalog); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Catalog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IClothingUseCase_GetItemByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItemByID'
type IClothingUseCase_GetItemByID_Call struct {
	*mock.Call
}

// GetItemByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *IClothingUseCase_Expecter) GetItemByID(ctx interface{}, id interface{}) *IClothingUseCase_GetItemByID_Call {
	return &IClothingUseCase_GetItemByID_Call{Call: _e.mock.On("GetItemByID", ctx, id)}
}

func (_c *IClothingUseCase_GetItemByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *IClothingUseCase_GetItemByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *IClothingUseCase_GetItemByID_Call) Return(_a0 *entity.Catalog, _a1 error) *IClothingUseCase_GetItemByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IClothingUseCase_GetItemByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Catalog, error)) *IClothingUseCase_GetItemByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItem provides a mock function with given fields: ctx, req, fileName, imageData
func (_m *IClothingUseCase) UpdateItem(ctx context.Context, req *entity.UpdateCatalogRequest, fileName string, imageData []byte) (*entity.Catalog, error) {
	ret := _m.Called(ctx, req, fileName, imageData)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItem")
	}

	var r0 *entity.Catalog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UpdateCatalogRequest, string, []byte) (*entity.Catalog, error)); ok {
		return rf(ctx, req, fileName, imageData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UpdateCatalogRequest, string, []byte) *entity.Catalog); ok {
		r0 = rf(ctx, req, fileName, imageData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Catalog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.UpdateCatalogRequest, string, []byte) error); ok {
		r1 = rf(ctx, req, fileName, imageData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IClothingUseCase_UpdateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItem'
type IClothingUseCase_UpdateItem_Call struct {
	*mock.Call
}

// UpdateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entity.UpdateCatalogRequest
//   - fileName string
//   - imageData []byte
func (_e *IClothingUseCase_Expecter) UpdateItem(ctx interface{}, req interface{}, fileName interface{}, imageData interface{}) *IClothingUseCase_UpdateItem_Call {
	return &IClothingUseCase_UpdateItem_Call{Call: _e.mock.On("UpdateItem", ctx, req, fileName, imageData)}
}

func (_c *IClothingUseCase_UpdateItem_Call) Run(run func(ctx context.Context, req *entity.UpdateCatalogRequest, fileName string, imageData []byte)) *IClothingUseCase_UpdateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.UpdateCatalogRequest), args[2].(string), args[3].([]byte))
	})
	return _c
}

func (_c *IClothingUseCase_UpdateItem_Call) Return(_a0 *entity.Catalog, _a1 error) *IClothingUseCase_UpdateItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IClothingUseCase_UpdateItem_Call) RunAndReturn(run func(context.Context, *entity.UpdateCatalogRequest, string, []byte) (*entity.Catalog, error)) *IClothingUseCase_UpdateItem_Call {
	_c.Call.Return(run)
	return _c
}

// NewIClothingUseCase creates a new instance of IClothingUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIClothingUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IClothingUseCase {
	mock := &IClothingUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
