// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "user_service/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// ISsoRepository is an autogenerated mock type for the ISsoRepository type
type ISsoRepository struct {
	mock.Mock
}

type ISsoRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ISsoRepository) EXPECT() *ISsoRepository_Expecter {
	return &ISsoRepository_Expecter{mock: &_m.Mock}
}

// DeleteUser provides a mock function with given fields: ctx, id
func (_m *ISsoRepository) DeleteUser(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ISsoRepository_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type ISsoRepository_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *ISsoRepository_Expecter) DeleteUser(ctx interface{}, id interface{}) *ISsoRepository_DeleteUser_Call {
	return &ISsoRepository_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *ISsoRepository_DeleteUser_Call) Run(run func(ctx context.Context, id int)) *ISsoRepository_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *ISsoRepository_DeleteUser_Call) Return(_a0 error) *ISsoRepository_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ISsoRepository_DeleteUser_Call) RunAndReturn(run func(context.Context, int) error) *ISsoRepository_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, email
func (_m *ISsoRepository) GetUser(ctx context.Context, email string) (entity.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entity.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ISsoRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type ISsoRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *ISsoRepository_Expecter) GetUser(ctx interface{}, email interface{}) *ISsoRepository_GetUser_Call {
	return &ISsoRepository_GetUser_Call{Call: _e.mock.On("GetUser", ctx, email)}
}

func (_c *ISsoRepository_GetUser_Call) Run(run func(ctx context.Context, email string)) *ISsoRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ISsoRepository_GetUser_Call) Return(_a0 entity.User, _a1 error) *ISsoRepository_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ISsoRepository_GetUser_Call) RunAndReturn(run func(context.Context, string) (entity.User, error)) *ISsoRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserById provides a mock function with given fields: ctx, id
func (_m *ISsoRepository) GetUserById(ctx context.Context, id int) (entity.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (entity.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) entity.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ISsoRepository_GetUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserById'
type ISsoRepository_GetUserById_Call struct {
	*mock.Call
}

// GetUserById is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *ISsoRepository_Expecter) GetUserById(ctx interface{}, id interface{}) *ISsoRepository_GetUserById_Call {
	return &ISsoRepository_GetUserById_Call{Call: _e.mock.On("GetUserById", ctx, id)}
}

func (_c *ISsoRepository_GetUserById_Call) Run(run func(ctx context.Context, id int)) *ISsoRepository_GetUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *ISsoRepository_GetUserById_Call) Return(_a0 entity.User, _a1 error) *ISsoRepository_GetUserById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ISsoRepository_GetUserById_Call) RunAndReturn(run func(context.Context, int) (entity.User, error)) *ISsoRepository_GetUserById_Call {
	_c.Call.Return(run)
	return _c
}

// SaveUser provides a mock function with given fields: ctx, email, password, username
func (_m *ISsoRepository) SaveUser(ctx context.Context, email string, password []byte, username string) (int, error) {
	ret := _m.Called(ctx, email, password, username)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, string) (int, error)); ok {
		return rf(ctx, email, password, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, string) int); ok {
		r0 = rf(ctx, email, password, username)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte, string) error); ok {
		r1 = rf(ctx, email, password, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ISsoRepository_SaveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveUser'
type ISsoRepository_SaveUser_Call struct {
	*mock.Call
}

// SaveUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password []byte
//   - username string
func (_e *ISsoRepository_Expecter) SaveUser(ctx interface{}, email interface{}, password interface{}, username interface{}) *ISsoRepository_SaveUser_Call {
	return &ISsoRepository_SaveUser_Call{Call: _e.mock.On("SaveUser", ctx, email, password, username)}
}

func (_c *ISsoRepository_SaveUser_Call) Run(run func(ctx context.Context, email string, password []byte, username string)) *ISsoRepository_SaveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), args[3].(string))
	})
	return _c
}

func (_c *ISsoRepository_SaveUser_Call) Return(_a0 int, _a1 error) *ISsoRepository_SaveUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ISsoRepository_SaveUser_Call) RunAndReturn(run func(context.Context, string, []byte, string) (int, error)) *ISsoRepository_SaveUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, newUser
func (_m *ISsoRepository) UpdateUser(ctx context.Context, newUser entity.User) (entity.User, error) {
	ret := _m.Called(ctx, newUser)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.User) (entity.User, error)); ok {
		return rf(ctx, newUser)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.User) entity.User); ok {
		r0 = rf(ctx, newUser)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.User) error); ok {
		r1 = rf(ctx, newUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ISsoRepository_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type ISsoRepository_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - newUser entity.User
func (_e *ISsoRepository_Expecter) UpdateUser(ctx interface{}, newUser interface{}) *ISsoRepository_UpdateUser_Call {
	return &ISsoRepository_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, newUser)}
}

func (_c *ISsoRepository_UpdateUser_Call) Run(run func(ctx context.Context, newUser entity.User)) *ISsoRepository_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.User))
	})
	return _c
}

func (_c *ISsoRepository_UpdateUser_Call) Return(_a0 entity.User, _a1 error) *ISsoRepository_UpdateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ISsoRepository_UpdateUser_Call) RunAndReturn(run func(context.Context, entity.User) (entity.User, error)) *ISsoRepository_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewISsoRepository creates a new instance of ISsoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISsoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISsoRepository {
	mock := &ISsoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
