// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "github.com/k1v4/drip_mate/internal/modules/notification_service/entity"

	mock "github.com/stretchr/testify/mock"
)

// EmailClient is an autogenerated mock type for the EmailClient type
type EmailClient struct {
	mock.Mock
}

type EmailClient_Expecter struct {
	mock *mock.Mock
}

func (_m *EmailClient) EXPECT() *EmailClient_Expecter {
	return &EmailClient_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: email
func (_m *EmailClient) Send(email *entity.Email) (*entity.SendResult, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 *entity.SendResult
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.Email) (*entity.SendResult, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(*entity.Email) *entity.SendResult); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.SendResult)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.Email) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EmailClient_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type EmailClient_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - email *entity.Email
func (_e *EmailClient_Expecter) Send(email interface{}) *EmailClient_Send_Call {
	return &EmailClient_Send_Call{Call: _e.mock.On("Send", email)}
}

func (_c *EmailClient_Send_Call) Run(run func(email *entity.Email)) *EmailClient_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.Email))
	})
	return _c
}

func (_c *EmailClient_Send_Call) Return(_a0 *entity.SendResult, _a1 error) *EmailClient_Send_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EmailClient_Send_Call) RunAndReturn(run func(*entity.Email) (*entity.SendResult, error)) *EmailClient_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewEmailClient creates a new instance of EmailClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailClient {
	mock := &EmailClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
