// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	internalentity "github.com/k1v4/drip_mate/internal/entity"
	entity "github.com/k1v4/drip_mate/internal/modules/user_service/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ISsoService is an autogenerated mock type for the ISsoService type
type ISsoService struct {
	mock.Mock
}

type ISsoService_Expecter struct {
	mock *mock.Mock
}

func (_m *ISsoService) EXPECT() *ISsoService_Expecter {
	return &ISsoService_Expecter{mock: &_m.Mock}
}

// DeleteAccount provides a mock function with given fields: ctx, id
func (_m *ISsoService) DeleteAccount(ctx context.Context, id string) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ISsoService_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type ISsoService_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ISsoService_Expecter) DeleteAccount(ctx interface{}, id interface{}) *ISsoService_DeleteAccount_Call {
	return &ISsoService_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", ctx, id)}
}

func (_c *ISsoService_DeleteAccount_Call) Run(run func(ctx context.Context, id string)) *ISsoService_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ISsoService_DeleteAccount_Call) Return(_a0 bool, _a1 error) *ISsoService_DeleteAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ISsoService_DeleteAccount_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *ISsoService_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOutfit provides a mock function with given fields: ctx, userID, outfitID
func (_m *ISsoService) DeleteOutfit(ctx context.Context, userID uuid.UUID, outfitID uuid.UUID) error {
	ret := _m.Called(ctx, userID, outfitID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOutfit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, outfitID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ISsoService_DeleteOutfit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOutfit'
type ISsoService_DeleteOutfit_Call struct {
	*mock.Call
}

// DeleteOutfit is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - outfitID uuid.UUID
func (_e *ISsoService_Expecter) DeleteOutfit(ctx interface{}, userID interface{}, outfitID interface{}) *ISsoService_DeleteOutfit_Call {
	return &ISsoService_DeleteOutfit_Call{Call: _e.mock.On("DeleteOutfit", ctx, userID, outfitID)}
}

func (_c *ISsoService_DeleteOutfit_Call) Run(run func(ctx context.Context, userID uuid.UUID, outfitID uuid.UUID)) *ISsoService_DeleteOutfit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *ISsoService_DeleteOutfit_Call) Return(_a0 error) *ISsoService_DeleteOutfit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ISsoService_DeleteOutfit_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *ISsoService_DeleteOutfit_Call {
	_c.Call.Return(run)
	return _c
}

// GetOutfits provides a mock function with given fields: ctx, userID
func (_m *ISsoService) GetOutfits(ctx context.Context, userID uuid.UUID) ([]entity.Outfit, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOutfits")
	}

	var r0 []entity.Outfit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.Outfit, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.Outfit); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Outfit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ISsoService_GetOutfits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOutfits'
type ISsoService_GetOutfits_Call struct {
	*mock.Call
}

// GetOutfits is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *ISsoService_Expecter) GetOutfits(ctx interface{}, userID interface{}) *ISsoService_GetOutfits_Call {
	return &ISsoService_GetOutfits_Call{Call: _e.mock.On("GetOutfits", ctx, userID)}
}

func (_c *ISsoService_GetOutfits_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *ISsoService_GetOutfits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ISsoService_GetOutfits_Call) Return(_a0 []entity.Outfit, _a1 error) *ISsoService_GetOutfits_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ISsoService_GetOutfits_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entity.Outfit, error)) *ISsoService_GetOutfits_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, userID
func (_m *ISsoService) GetUserByID(ctx context.Context, userID uuid.UUID) (*entity.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ISsoService_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type ISsoService_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *ISsoService_Expecter) GetUserByID(ctx interface{}, userID interface{}) *ISsoService_GetUserByID_Call {
	return &ISsoService_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *ISsoService_GetUserByID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *ISsoService_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ISsoService_GetUserByID_Call) Return(_a0 *entity.User, _a1 error) *ISsoService_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ISsoService_GetUserByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.User, error)) *ISsoService_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *ISsoService) Login(ctx context.Context, email string, password string) (internalentity.Role, string, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 internalentity.Role
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (internalentity.Role, string, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) internalentity.Role); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(internalentity.Role)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, email, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ISsoService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type ISsoService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *ISsoService_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *ISsoService_Login_Call {
	return &ISsoService_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *ISsoService_Login_Call) Run(run func(ctx context.Context, email string, password string)) *ISsoService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ISsoService_Login_Call) Return(_a0 internalentity.Role, _a1 string, _a2 error) *ISsoService_Login_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ISsoService_Login_Call) RunAndReturn(run func(context.Context, string, string) (internalentity.Role, string, error)) *ISsoService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, email, password
func (_m *ISsoService) Register(ctx context.Context, email string, password string) (internalentity.Role, string, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 internalentity.Role
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (internalentity.Role, string, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) internalentity.Role); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(internalentity.Role)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, email, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ISsoService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type ISsoService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *ISsoService_Expecter) Register(ctx interface{}, email interface{}, password interface{}) *ISsoService_Register_Call {
	return &ISsoService_Register_Call{Call: _e.mock.On("Register", ctx, email, password)}
}

func (_c *ISsoService_Register_Call) Run(run func(ctx context.Context, email string, password string)) *ISsoService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ISsoService_Register_Call) Return(_a0 internalentity.Role, _a1 string, _a2 error) *ISsoService_Register_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ISsoService_Register_Call) RunAndReturn(run func(context.Context, string, string) (internalentity.Role, string, error)) *ISsoService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOutfit provides a mock function with given fields: ctx, userID, saveItems
func (_m *ISsoService) SaveOutfit(ctx context.Context, userID uuid.UUID, saveItems entity.SaveOutfitRequest) (uuid.UUID, error) {
	ret := _m.Called(ctx, userID, saveItems)

	if len(ret) == 0 {
		panic("no return value specified for SaveOutfit")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.SaveOutfitRequest) (uuid.UUID, error)); ok {
		return rf(ctx, userID, saveItems)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.SaveOutfitRequest) uuid.UUID); ok {
		r0 = rf(ctx, userID, saveItems)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, entity.SaveOutfitRequest) error); ok {
		r1 = rf(ctx, userID, saveItems)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ISsoService_SaveOutfit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOutfit'
type ISsoService_SaveOutfit_Call struct {
	*mock.Call
}

// SaveOutfit is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - saveItems entity.SaveOutfitRequest
func (_e *ISsoService_Expecter) SaveOutfit(ctx interface{}, userID interface{}, saveItems interface{}) *ISsoService_SaveOutfit_Call {
	return &ISsoService_SaveOutfit_Call{Call: _e.mock.On("SaveOutfit", ctx, userID, saveItems)}
}

func (_c *ISsoService_SaveOutfit_Call) Run(run func(ctx context.Context, userID uuid.UUID, saveItems entity.SaveOutfitRequest)) *ISsoService_SaveOutfit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(entity.SaveOutfitRequest))
	})
	return _c
}

func (_c *ISsoService_SaveOutfit_Call) Return(_a0 uuid.UUID, _a1 error) *ISsoService_SaveOutfit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ISsoService_SaveOutfit_Call) RunAndReturn(run func(context.Context, uuid.UUID, entity.SaveOutfitRequest) (uuid.UUID, error)) *ISsoService_SaveOutfit_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateContext provides a mock function with given fields: ctx, userID, req
func (_m *ISsoService) UpdateContext(ctx context.Context, userID uuid.UUID, req *entity.UpdateContext) error {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *entity.UpdateContext) error); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ISsoService_UpdateContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateContext'
type ISsoService_UpdateContext_Call struct {
	*mock.Call
}

// UpdateContext is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req *entity.UpdateContext
func (_e *ISsoService_Expecter) UpdateContext(ctx interface{}, userID interface{}, req interface{}) *ISsoService_UpdateContext_Call {
	return &ISsoService_UpdateContext_Call{Call: _e.mock.On("UpdateContext", ctx, userID, req)}
}

func (_c *ISsoService_UpdateContext_Call) Run(run func(ctx context.Context, userID uuid.UUID, req *entity.UpdateContext)) *ISsoService_UpdateContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*entity.UpdateContext))
	})
	return _c
}

func (_c *ISsoService_UpdateContext_Call) Return(_a0 error) *ISsoService_UpdateContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ISsoService_UpdateContext_Call) RunAndReturn(run func(context.Context, uuid.UUID, *entity.UpdateContext) error) *ISsoService_UpdateContext_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function with given fields: ctx, id, pass
func (_m *ISsoService) UpdatePassword(ctx context.Context, id uuid.UUID, pass *entity.UpdatePass) error {
	ret := _m.Called(ctx, id, pass)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *entity.UpdatePass) error); ok {
		r0 = rf(ctx, id, pass)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ISsoService_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type ISsoService_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - pass *entity.UpdatePass
func (_e *ISsoService_Expecter) UpdatePassword(ctx interface{}, id interface{}, pass interface{}) *ISsoService_UpdatePassword_Call {
	return &ISsoService_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, id, pass)}
}

func (_c *ISsoService_UpdatePassword_Call) Run(run func(ctx context.Context, id uuid.UUID, pass *entity.UpdatePass)) *ISsoService_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*entity.UpdatePass))
	})
	return _c
}

func (_c *ISsoService_UpdatePassword_Call) Return(_a0 error) *ISsoService_UpdatePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ISsoService_UpdatePassword_Call) RunAndReturn(run func(context.Context, uuid.UUID, *entity.UpdatePass) error) *ISsoService_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserInfo provides a mock function with given fields: ctx, id, name, surname, username, gender
func (_m *ISsoService) UpdateUserInfo(ctx context.Context, id string, name string, surname string, username string, gender string) (*entity.User, error) {
	ret := _m.Called(ctx, id, name, surname, username, gender)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserInfo")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) (*entity.User, error)); ok {
		return rf(ctx, id, name, surname, username, gender)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) *entity.User); ok {
		r0 = rf(ctx, id, name, surname, username, gender)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string) error); ok {
		r1 = rf(ctx, id, name, surname, username, gender)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ISsoService_UpdateUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserInfo'
type ISsoService_UpdateUserInfo_Call struct {
	*mock.Call
}

// UpdateUserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - name string
//   - surname string
//   - username string
//   - gender string
func (_e *ISsoService_Expecter) UpdateUserInfo(ctx interface{}, id interface{}, name interface{}, surname interface{}, username interface{}, gender interface{}) *ISsoService_UpdateUserInfo_Call {
	return &ISsoService_UpdateUserInfo_Call{Call: _e.mock.On("UpdateUserInfo", ctx, id, name, surname, username, gender)}
}

func (_c *ISsoService_UpdateUserInfo_Call) Run(run func(ctx context.Context, id string, name string, surname string, username string, gender string)) *ISsoService_UpdateUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *ISsoService_UpdateUserInfo_Call) Return(_a0 *entity.User, _a1 error) *ISsoService_UpdateUserInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ISsoService_UpdateUserInfo_Call) RunAndReturn(run func(context.Context, string, string, string, string, string) (*entity.User, error)) *ISsoService_UpdateUserInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewISsoService creates a new instance of ISsoService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISsoService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISsoService {
	mock := &ISsoService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
