// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/k1v4/drip_mate/internal/modules/user_service/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ISsoRepository is an autogenerated mock type for the ISsoRepository type
type ISsoRepository struct {
	mock.Mock
}

type ISsoRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ISsoRepository) EXPECT() *ISsoRepository_Expecter {
	return &ISsoRepository_Expecter{mock: &_m.Mock}
}

// DeleteOutfit provides a mock function with given fields: ctx, userID, outfitID
func (_m *ISsoRepository) DeleteOutfit(ctx context.Context, userID uuid.UUID, outfitID uuid.UUID) error {
	ret := _m.Called(ctx, userID, outfitID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOutfit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, outfitID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ISsoRepository_DeleteOutfit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOutfit'
type ISsoRepository_DeleteOutfit_Call struct {
	*mock.Call
}

// DeleteOutfit is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - outfitID uuid.UUID
func (_e *ISsoRepository_Expecter) DeleteOutfit(ctx interface{}, userID interface{}, outfitID interface{}) *ISsoRepository_DeleteOutfit_Call {
	return &ISsoRepository_DeleteOutfit_Call{Call: _e.mock.On("DeleteOutfit", ctx, userID, outfitID)}
}

func (_c *ISsoRepository_DeleteOutfit_Call) Run(run func(ctx context.Context, userID uuid.UUID, outfitID uuid.UUID)) *ISsoRepository_DeleteOutfit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *ISsoRepository_DeleteOutfit_Call) Return(_a0 error) *ISsoRepository_DeleteOutfit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ISsoRepository_DeleteOutfit_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *ISsoRepository_DeleteOutfit_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: ctx, id
func (_m *ISsoRepository) DeleteUser(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ISsoRepository_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type ISsoRepository_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ISsoRepository_Expecter) DeleteUser(ctx interface{}, id interface{}) *ISsoRepository_DeleteUser_Call {
	return &ISsoRepository_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *ISsoRepository_DeleteUser_Call) Run(run func(ctx context.Context, id string)) *ISsoRepository_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ISsoRepository_DeleteUser_Call) Return(_a0 error) *ISsoRepository_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ISsoRepository_DeleteUser_Call) RunAndReturn(run func(context.Context, string) error) *ISsoRepository_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, email
func (_m *ISsoRepository) GetUser(ctx context.Context, email string) (*entity.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ISsoRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type ISsoRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *ISsoRepository_Expecter) GetUser(ctx interface{}, email interface{}) *ISsoRepository_GetUser_Call {
	return &ISsoRepository_GetUser_Call{Call: _e.mock.On("GetUser", ctx, email)}
}

func (_c *ISsoRepository_GetUser_Call) Run(run func(ctx context.Context, email string)) *ISsoRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ISsoRepository_GetUser_Call) Return(_a0 *entity.User, _a1 error) *ISsoRepository_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ISsoRepository_GetUser_Call) RunAndReturn(run func(context.Context, string) (*entity.User, error)) *ISsoRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserById provides a mock function with given fields: ctx, id
func (_m *ISsoRepository) GetUserById(ctx context.Context, id string) (*entity.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ISsoRepository_GetUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserById'
type ISsoRepository_GetUserById_Call struct {
	*mock.Call
}

// GetUserById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ISsoRepository_Expecter) GetUserById(ctx interface{}, id interface{}) *ISsoRepository_GetUserById_Call {
	return &ISsoRepository_GetUserById_Call{Call: _e.mock.On("GetUserById", ctx, id)}
}

func (_c *ISsoRepository_GetUserById_Call) Run(run func(ctx context.Context, id string)) *ISsoRepository_GetUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ISsoRepository_GetUserById_Call) Return(_a0 *entity.User, _a1 error) *ISsoRepository_GetUserById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ISsoRepository_GetUserById_Call) RunAndReturn(run func(context.Context, string) (*entity.User, error)) *ISsoRepository_GetUserById_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserOutfits provides a mock function with given fields: ctx, userID
func (_m *ISsoRepository) GetUserOutfits(ctx context.Context, userID uuid.UUID) ([]entity.Outfit, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserOutfits")
	}

	var r0 []entity.Outfit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.Outfit, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.Outfit); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Outfit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ISsoRepository_GetUserOutfits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserOutfits'
type ISsoRepository_GetUserOutfits_Call struct {
	*mock.Call
}

// GetUserOutfits is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *ISsoRepository_Expecter) GetUserOutfits(ctx interface{}, userID interface{}) *ISsoRepository_GetUserOutfits_Call {
	return &ISsoRepository_GetUserOutfits_Call{Call: _e.mock.On("GetUserOutfits", ctx, userID)}
}

func (_c *ISsoRepository_GetUserOutfits_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *ISsoRepository_GetUserOutfits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ISsoRepository_GetUserOutfits_Call) Return(_a0 []entity.Outfit, _a1 error) *ISsoRepository_GetUserOutfits_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ISsoRepository_GetUserOutfits_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entity.Outfit, error)) *ISsoRepository_GetUserOutfits_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOutfit provides a mock function with given fields: ctx, userID, saveItems
func (_m *ISsoRepository) SaveOutfit(ctx context.Context, userID uuid.UUID, saveItems entity.SaveOutfitRequest) (uuid.UUID, error) {
	ret := _m.Called(ctx, userID, saveItems)

	if len(ret) == 0 {
		panic("no return value specified for SaveOutfit")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.SaveOutfitRequest) (uuid.UUID, error)); ok {
		return rf(ctx, userID, saveItems)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.SaveOutfitRequest) uuid.UUID); ok {
		r0 = rf(ctx, userID, saveItems)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, entity.SaveOutfitRequest) error); ok {
		r1 = rf(ctx, userID, saveItems)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ISsoRepository_SaveOutfit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOutfit'
type ISsoRepository_SaveOutfit_Call struct {
	*mock.Call
}

// SaveOutfit is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - saveItems entity.SaveOutfitRequest
func (_e *ISsoRepository_Expecter) SaveOutfit(ctx interface{}, userID interface{}, saveItems interface{}) *ISsoRepository_SaveOutfit_Call {
	return &ISsoRepository_SaveOutfit_Call{Call: _e.mock.On("SaveOutfit", ctx, userID, saveItems)}
}

func (_c *ISsoRepository_SaveOutfit_Call) Run(run func(ctx context.Context, userID uuid.UUID, saveItems entity.SaveOutfitRequest)) *ISsoRepository_SaveOutfit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(entity.SaveOutfitRequest))
	})
	return _c
}

func (_c *ISsoRepository_SaveOutfit_Call) Return(_a0 uuid.UUID, _a1 error) *ISsoRepository_SaveOutfit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ISsoRepository_SaveOutfit_Call) RunAndReturn(run func(context.Context, uuid.UUID, entity.SaveOutfitRequest) (uuid.UUID, error)) *ISsoRepository_SaveOutfit_Call {
	_c.Call.Return(run)
	return _c
}

// SaveUser provides a mock function with given fields: ctx, email, password
func (_m *ISsoRepository) SaveUser(ctx context.Context, email string, password string) (string, int, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 string
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, int, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) int); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, email, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ISsoRepository_SaveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveUser'
type ISsoRepository_SaveUser_Call struct {
	*mock.Call
}

// SaveUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *ISsoRepository_Expecter) SaveUser(ctx interface{}, email interface{}, password interface{}) *ISsoRepository_SaveUser_Call {
	return &ISsoRepository_SaveUser_Call{Call: _e.mock.On("SaveUser", ctx, email, password)}
}

func (_c *ISsoRepository_SaveUser_Call) Run(run func(ctx context.Context, email string, password string)) *ISsoRepository_SaveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ISsoRepository_SaveUser_Call) Return(_a0 string, _a1 int, _a2 error) *ISsoRepository_SaveUser_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ISsoRepository_SaveUser_Call) RunAndReturn(run func(context.Context, string, string) (string, int, error)) *ISsoRepository_SaveUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function with given fields: ctx, userID, newPasswordHash
func (_m *ISsoRepository) UpdatePassword(ctx context.Context, userID uuid.UUID, newPasswordHash string) error {
	ret := _m.Called(ctx, userID, newPasswordHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userID, newPasswordHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ISsoRepository_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type ISsoRepository_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - newPasswordHash string
func (_e *ISsoRepository_Expecter) UpdatePassword(ctx interface{}, userID interface{}, newPasswordHash interface{}) *ISsoRepository_UpdatePassword_Call {
	return &ISsoRepository_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, userID, newPasswordHash)}
}

func (_c *ISsoRepository_UpdatePassword_Call) Run(run func(ctx context.Context, userID uuid.UUID, newPasswordHash string)) *ISsoRepository_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *ISsoRepository_UpdatePassword_Call) Return(_a0 error) *ISsoRepository_UpdatePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ISsoRepository_UpdatePassword_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *ISsoRepository_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserContext provides a mock function with given fields: ctx, req
func (_m *ISsoRepository) UpdateUserContext(ctx context.Context, req *entity.UpdateContext) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UpdateContext) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ISsoRepository_UpdateUserContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserContext'
type ISsoRepository_UpdateUserContext_Call struct {
	*mock.Call
}

// UpdateUserContext is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entity.UpdateContext
func (_e *ISsoRepository_Expecter) UpdateUserContext(ctx interface{}, req interface{}) *ISsoRepository_UpdateUserContext_Call {
	return &ISsoRepository_UpdateUserContext_Call{Call: _e.mock.On("UpdateUserContext", ctx, req)}
}

func (_c *ISsoRepository_UpdateUserContext_Call) Run(run func(ctx context.Context, req *entity.UpdateContext)) *ISsoRepository_UpdateUserContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.UpdateContext))
	})
	return _c
}

func (_c *ISsoRepository_UpdateUserContext_Call) Return(_a0 error) *ISsoRepository_UpdateUserContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ISsoRepository_UpdateUserContext_Call) RunAndReturn(run func(context.Context, *entity.UpdateContext) error) *ISsoRepository_UpdateUserContext_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserOutfitLog provides a mock function with given fields: ctx, logID
func (_m *ISsoRepository) UpdateUserOutfitLog(ctx context.Context, logID int) error {
	ret := _m.Called(ctx, logID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserOutfitLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, logID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ISsoRepository_UpdateUserOutfitLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserOutfitLog'
type ISsoRepository_UpdateUserOutfitLog_Call struct {
	*mock.Call
}

// UpdateUserOutfitLog is a helper method to define mock.On call
//   - ctx context.Context
//   - logID int
func (_e *ISsoRepository_Expecter) UpdateUserOutfitLog(ctx interface{}, logID interface{}) *ISsoRepository_UpdateUserOutfitLog_Call {
	return &ISsoRepository_UpdateUserOutfitLog_Call{Call: _e.mock.On("UpdateUserOutfitLog", ctx, logID)}
}

func (_c *ISsoRepository_UpdateUserOutfitLog_Call) Run(run func(ctx context.Context, logID int)) *ISsoRepository_UpdateUserOutfitLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *ISsoRepository_UpdateUserOutfitLog_Call) Return(_a0 error) *ISsoRepository_UpdateUserOutfitLog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ISsoRepository_UpdateUserOutfitLog_Call) RunAndReturn(run func(context.Context, int) error) *ISsoRepository_UpdateUserOutfitLog_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserPersonal provides a mock function with given fields: ctx, newUser
func (_m *ISsoRepository) UpdateUserPersonal(ctx context.Context, newUser *entity.UpdatePersonal) (string, error) {
	ret := _m.Called(ctx, newUser)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserPersonal")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UpdatePersonal) (string, error)); ok {
		return rf(ctx, newUser)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UpdatePersonal) string); ok {
		r0 = rf(ctx, newUser)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.UpdatePersonal) error); ok {
		r1 = rf(ctx, newUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ISsoRepository_UpdateUserPersonal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserPersonal'
type ISsoRepository_UpdateUserPersonal_Call struct {
	*mock.Call
}

// UpdateUserPersonal is a helper method to define mock.On call
//   - ctx context.Context
//   - newUser *entity.UpdatePersonal
func (_e *ISsoRepository_Expecter) UpdateUserPersonal(ctx interface{}, newUser interface{}) *ISsoRepository_UpdateUserPersonal_Call {
	return &ISsoRepository_UpdateUserPersonal_Call{Call: _e.mock.On("UpdateUserPersonal", ctx, newUser)}
}

func (_c *ISsoRepository_UpdateUserPersonal_Call) Run(run func(ctx context.Context, newUser *entity.UpdatePersonal)) *ISsoRepository_UpdateUserPersonal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.UpdatePersonal))
	})
	return _c
}

func (_c *ISsoRepository_UpdateUserPersonal_Call) Return(_a0 string, _a1 error) *ISsoRepository_UpdateUserPersonal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ISsoRepository_UpdateUserPersonal_Call) RunAndReturn(run func(context.Context, *entity.UpdatePersonal) (string, error)) *ISsoRepository_UpdateUserPersonal_Call {
	_c.Call.Return(run)
	return _c
}

// NewISsoRepository creates a new instance of ISsoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISsoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISsoRepository {
	mock := &ISsoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
