// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/k1v4/drip_mate/user_service/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// ISsoService is an autogenerated mock type for the ISsoService type
type ISsoService struct {
	mock.Mock
}

type ISsoService_Expecter struct {
	mock *mock.Mock
}

func (_m *ISsoService) EXPECT() *ISsoService_Expecter {
	return &ISsoService_Expecter{mock: &_m.Mock}
}

// DeleteAccount provides a mock function with given fields: ctx, id
func (_m *ISsoService) DeleteAccount(ctx context.Context, id int) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ISsoService_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type ISsoService_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *ISsoService_Expecter) DeleteAccount(ctx interface{}, id interface{}) *ISsoService_DeleteAccount_Call {
	return &ISsoService_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", ctx, id)}
}

func (_c *ISsoService_DeleteAccount_Call) Run(run func(ctx context.Context, id int)) *ISsoService_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *ISsoService_DeleteAccount_Call) Return(_a0 bool, _a1 error) *ISsoService_DeleteAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ISsoService_DeleteAccount_Call) RunAndReturn(run func(context.Context, int) (bool, error)) *ISsoService_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *ISsoService) Login(ctx context.Context, email string, password string) (int, string, string, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 int
	var r1 string
	var r2 string
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int, string, string, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) string); ok {
		r2 = rf(ctx, email, password)
	} else {
		r2 = ret.Get(2).(string)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, string) error); ok {
		r3 = rf(ctx, email, password)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// ISsoService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type ISsoService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *ISsoService_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *ISsoService_Login_Call {
	return &ISsoService_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *ISsoService_Login_Call) Run(run func(ctx context.Context, email string, password string)) *ISsoService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ISsoService_Login_Call) Return(_a0 int, _a1 string, _a2 string, _a3 error) *ISsoService_Login_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *ISsoService_Login_Call) RunAndReturn(run func(context.Context, string, string) (int, string, string, error)) *ISsoService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function with given fields: ctx, token
func (_m *ISsoService) RefreshToken(ctx context.Context, token string) (string, string, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, string, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, token)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ISsoService_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type ISsoService_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *ISsoService_Expecter) RefreshToken(ctx interface{}, token interface{}) *ISsoService_RefreshToken_Call {
	return &ISsoService_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, token)}
}

func (_c *ISsoService_RefreshToken_Call) Run(run func(ctx context.Context, token string)) *ISsoService_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ISsoService_RefreshToken_Call) Return(_a0 string, _a1 string, _a2 error) *ISsoService_RefreshToken_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ISsoService_RefreshToken_Call) RunAndReturn(run func(context.Context, string) (string, string, error)) *ISsoService_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, email, password, username
func (_m *ISsoService) Register(ctx context.Context, email string, password string, username string) (int, error) {
	ret := _m.Called(ctx, email, password, username)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (int, error)); ok {
		return rf(ctx, email, password, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) int); ok {
		r0 = rf(ctx, email, password, username)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, email, password, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ISsoService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type ISsoService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
//   - username string
func (_e *ISsoService_Expecter) Register(ctx interface{}, email interface{}, password interface{}, username interface{}) *ISsoService_Register_Call {
	return &ISsoService_Register_Call{Call: _e.mock.On("Register", ctx, email, password, username)}
}

func (_c *ISsoService_Register_Call) Run(run func(ctx context.Context, email string, password string, username string)) *ISsoService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ISsoService_Register_Call) Return(_a0 int, _a1 error) *ISsoService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ISsoService_Register_Call) RunAndReturn(run func(context.Context, string, string, string) (int, error)) *ISsoService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserInfo provides a mock function with given fields: ctx, id, email, password, name, surname, username
func (_m *ISsoService) UpdateUserInfo(ctx context.Context, id int, email string, password string, name string, surname string, username string) (entity.User, error) {
	ret := _m.Called(ctx, id, email, password, name, surname, username)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserInfo")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string, string, string, string) (entity.User, error)); ok {
		return rf(ctx, id, email, password, name, surname, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string, string, string, string) entity.User); ok {
		r0 = rf(ctx, id, email, password, name, surname, username)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string, string, string, string, string) error); ok {
		r1 = rf(ctx, id, email, password, name, surname, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ISsoService_UpdateUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserInfo'
type ISsoService_UpdateUserInfo_Call struct {
	*mock.Call
}

// UpdateUserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - email string
//   - password string
//   - name string
//   - surname string
//   - username string
func (_e *ISsoService_Expecter) UpdateUserInfo(ctx interface{}, id interface{}, email interface{}, password interface{}, name interface{}, surname interface{}, username interface{}) *ISsoService_UpdateUserInfo_Call {
	return &ISsoService_UpdateUserInfo_Call{Call: _e.mock.On("UpdateUserInfo", ctx, id, email, password, name, surname, username)}
}

func (_c *ISsoService_UpdateUserInfo_Call) Run(run func(ctx context.Context, id int, email string, password string, name string, surname string, username string)) *ISsoService_UpdateUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string), args[3].(string), args[4].(string), args[5].(string), args[6].(string))
	})
	return _c
}

func (_c *ISsoService_UpdateUserInfo_Call) Return(_a0 entity.User, _a1 error) *ISsoService_UpdateUserInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ISsoService_UpdateUserInfo_Call) RunAndReturn(run func(context.Context, int, string, string, string, string, string) (entity.User, error)) *ISsoService_UpdateUserInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewISsoService creates a new instance of ISsoService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISsoService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISsoService {
	mock := &ISsoService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
