// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IUseCase is an autogenerated mock type for the IUseCase type
type IUseCase struct {
	mock.Mock
}

type IUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *IUseCase) EXPECT() *IUseCase_Expecter {
	return &IUseCase_Expecter{mock: &_m.Mock}
}

// SendEmailNotification provides a mock function with given fields: ctx, text, email
func (_m *IUseCase) SendEmailNotification(ctx context.Context, text string, email string) error {
	ret := _m.Called(ctx, text, email)

	if len(ret) == 0 {
		panic("no return value specified for SendEmailNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, text, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IUseCase_SendEmailNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmailNotification'
type IUseCase_SendEmailNotification_Call struct {
	*mock.Call
}

// SendEmailNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
//   - email string
func (_e *IUseCase_Expecter) SendEmailNotification(ctx interface{}, text interface{}, email interface{}) *IUseCase_SendEmailNotification_Call {
	return &IUseCase_SendEmailNotification_Call{Call: _e.mock.On("SendEmailNotification", ctx, text, email)}
}

func (_c *IUseCase_SendEmailNotification_Call) Run(run func(ctx context.Context, text string, email string)) *IUseCase_SendEmailNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *IUseCase_SendEmailNotification_Call) Return(_a0 error) *IUseCase_SendEmailNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IUseCase_SendEmailNotification_Call) RunAndReturn(run func(context.Context, string, string) error) *IUseCase_SendEmailNotification_Call {
	_c.Call.Return(run)
	return _c
}

// NewIUseCase creates a new instance of IUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUseCase {
	mock := &IUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
