// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/k1v4/drip_mate/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MLProvider is an autogenerated mock type for the MLProvider type
type MLProvider struct {
	mock.Mock
}

type MLProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MLProvider) EXPECT() *MLProvider_Expecter {
	return &MLProvider_Expecter{mock: &_m.Mock}
}

// GetRecommendation provides a mock function with given fields: ctx, data
func (_m *MLProvider) GetRecommendation(ctx context.Context, data *entity.RequestData) ([]entity.OutfitItem, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for GetRecommendation")
	}

	var r0 []entity.OutfitItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.RequestData) ([]entity.OutfitItem, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.RequestData) []entity.OutfitItem); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.OutfitItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.RequestData) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MLProvider_GetRecommendation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecommendation'
type MLProvider_GetRecommendation_Call struct {
	*mock.Call
}

// GetRecommendation is a helper method to define mock.On call
//   - ctx context.Context
//   - data *entity.RequestData
func (_e *MLProvider_Expecter) GetRecommendation(ctx interface{}, data interface{}) *MLProvider_GetRecommendation_Call {
	return &MLProvider_GetRecommendation_Call{Call: _e.mock.On("GetRecommendation", ctx, data)}
}

func (_c *MLProvider_GetRecommendation_Call) Run(run func(ctx context.Context, data *entity.RequestData)) *MLProvider_GetRecommendation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.RequestData))
	})
	return _c
}

func (_c *MLProvider_GetRecommendation_Call) Return(_a0 []entity.OutfitItem, _a1 error) *MLProvider_GetRecommendation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MLProvider_GetRecommendation_Call) RunAndReturn(run func(context.Context, *entity.RequestData) ([]entity.OutfitItem, error)) *MLProvider_GetRecommendation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMLProvider creates a new instance of MLProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMLProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MLProvider {
	mock := &MLProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
