// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/k1v4/drip_mate/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// WeatherProvider is an autogenerated mock type for the WeatherProvider type
type WeatherProvider struct {
	mock.Mock
}

type WeatherProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *WeatherProvider) EXPECT() *WeatherProvider_Expecter {
	return &WeatherProvider_Expecter{mock: &_m.Mock}
}

// GetCurrentWeather provides a mock function with given fields: ctx, city
func (_m *WeatherProvider) GetCurrentWeather(ctx context.Context, city string) (*entity.Weather, error) {
	ret := _m.Called(ctx, city)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentWeather")
	}

	var r0 *entity.Weather
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Weather, error)); ok {
		return rf(ctx, city)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Weather); ok {
		r0 = rf(ctx, city)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Weather)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, city)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WeatherProvider_GetCurrentWeather_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentWeather'
type WeatherProvider_GetCurrentWeather_Call struct {
	*mock.Call
}

// GetCurrentWeather is a helper method to define mock.On call
//   - ctx context.Context
//   - city string
func (_e *WeatherProvider_Expecter) GetCurrentWeather(ctx interface{}, city interface{}) *WeatherProvider_GetCurrentWeather_Call {
	return &WeatherProvider_GetCurrentWeather_Call{Call: _e.mock.On("GetCurrentWeather", ctx, city)}
}

func (_c *WeatherProvider_GetCurrentWeather_Call) Run(run func(ctx context.Context, city string)) *WeatherProvider_GetCurrentWeather_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *WeatherProvider_GetCurrentWeather_Call) Return(_a0 *entity.Weather, _a1 error) *WeatherProvider_GetCurrentWeather_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WeatherProvider_GetCurrentWeather_Call) RunAndReturn(run func(context.Context, string) (*entity.Weather, error)) *WeatherProvider_GetCurrentWeather_Call {
	_c.Call.Return(run)
	return _c
}

// NewWeatherProvider creates a new instance of WeatherProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWeatherProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *WeatherProvider {
	mock := &WeatherProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
